DROP TABLE IF EXISTS project_tech CASCADE;
DROP TABLE IF EXISTS tech CASCADE;
DROP TABLE IF EXISTS project_member CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS JOB CASCADE;